-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Snowflake SampleDb0, v3 by a4vlad4a+enterprise@gmail.com *


CREATE FILE FORMAT CsvFileFormat
 TYPE = CSV
 COMPRESSION = BROTLI;

